export default [
  {
    rank: '1',
    location: 'Woodlands',
    score: 3578, 
    change: 'up',
    image: '../assets/imgs/redhill.jpg',
  },
  {
    rank: '2',
    location: 'Yishun',
    score: 3577, 
    change: 'up',
    image: '../assets/imgs/redhill.jpg',
  },
  {
    rank: '3',
    location: 'Beauty World',
    score: 3576, 
    change: 'up',
    image: '../assets/imgs/bukitpanjang.jpg',
  },
  {
    rank: '4',
    location: 'Bukit Panjang',
    score: 3575, 
    change: 'up',
    image: '../assets/imgs/redhill.jpg',
  },
  {
    rank: '5',
    location: 'Admiralty',
    score: 3575, 
    change: 'down',
    image: '../assets/imgs/redhill.jpg',
  },
  {
    rank: '6',
    location: 'Jurong East',
    score: 3575, 
    change: 'down',
    image: '../assets/imgs/redhill.jpg',
  },
  {
    rank: '7',
    location: 'Newton',
    score: 3575, 
    change: 'up',
    image: '../assets/imgs/redhill.jpg',
  },
  {
    rank: '8',
    location: 'Bras Basah',
    score: 3575, 
    change: 'up',
    image: '../assets/imgs/redhill.jpg',
  },
  {
    rank: '9',
    location: 'Bencoolen',
    score: 3575, 
    change: 'up',
    image: '../assets/imgs/redhill.jpg',
  },
  {
    rank: '10',
    location: 'City Hall',
    score: 3575, 
    change: 'down',
    image: '../assets/imgs/redhill.jpg',
  },

];